version: 2.1

jobs:
  build:
    docker:
      - image: java:17

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - mvn:
          install:
            options: "-DskipTests"

      - cache:
          paths:
            - ~/.m2/repository
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - mvn:
          test:
            jdk: openjdk17